streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/antimatter-open-publishing, user/themes/antimatter]
chromeless:
  enabled: false
git_sync_edit_note_text: 'Have a suggestion or correction?'
displaypostsummary:
  enabled: false
cc_license:
  enabled: false
  type: ccby
  icon: false
displaycustommenus:
  enabled: true
hidehomemenulink: false
display_of_git_sync_repo_link: none
type_of_git_sync_repo_link: edit
